model_list:
  # OpenAI Models (configure com sua chave)
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models (configure com sua chave)
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY

  # Adicione outros modelos conforme necessário

litellm_settings:
  # Configurações gerais
  set_verbose: true
  json_logs: true

general_settings:
  # Chave mestra para acessar o proxy
  master_key: "litellm-master-key-2025"
  
  # Configuração do banco de dados (opcional)
  # database_url: "sqlite:///litellm.db"
  
  # Interface UI habilitada
  ui_access_mode: "admin_only"
