model_list:
  # Modelo de teste sem API key (apenas para demonstração)
  - model_name: test-model
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: fake-key-for-testing

litellm_settings:
  # Configurações gerais
  set_verbose: true
  json_logs: true

general_settings:
  # Chave mestra para acessar o proxy
  master_key: "litellm-master-key-2025"
  
  # Interface UI habilitada
  ui_access_mode: "admin_only"
  
  # Desabilitar banco de dados
  store_model_in_db: false
